@endpoint = https://6uoymedl0f.execute-api.eu-west-2.amazonaws.com/prod

GET {{endpoint}}/hello
###

POST {{endpoint}}/spaces?spaceId=cda7955b-11b5-4f6f-8bf9-a59135ed40c6
Content-Type: application/json

{
    "location" : "London",
    "name" : "Best Location"
}
###